model:
  arch: mini_gpt4
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  freeze_llama: False
  max_txt_len: 160
  end_sym: "###"
  generation_prompt_path: "prompts/stage1-pretraining-prompts.txt"
  refinement_prompt_path: "prompts/stage1-pretraining-prompts.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '/path/to/linear/layer'
  is_pretraining: True

  use_contrastive_loss: False
  use_refinement_loss: False
  triplet_margin: 0.5
  triplet_weight: 1.0
  refinement_loss_weight: 1.0

  # lora configuartion
  use_lora: True                         # use lora for vicuna
  use_lora_vit_qformer: False            # use lora for vision backbone
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1

  # ZeRO optimizer configuration
  use_zero_optimizer: True
  deepspeed_config: "train_configs/stage1/zero.json"

datasets:
  mimic_generate_then_refine:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: mimic_generate_then_refine
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 10
  iters_per_epoch: 5000 # 200
  batch_size_train: 1 # total batch size, not per GPU
  batch_size_eval: 1
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "/path/to/output/dir"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 2
  dist_url: "env://"
  distributed: True

  # ZeRO optimizer configuration
  use_zero_optimizer: True
  deepspeed_config: "train_configs/stage1/zero.json"